チェックリストのJS制御を追加
dotinstall/setup pull request #1
Opened 2022-06-20 07:36 UTC by hxtksg

- チェックリストの追加
- チェックリストを JS で管理
- JS でチェックリストの描画

以上を追加しました。ご確認よろしくお願いいたします。 @taguchi

2022-06-20 07:52 UTC, taguchi requested changes
全体的にいい感じですー。こういうのがちゃっちゃかかけるとだいぶ効率化できますよね！細かい点がいくつかあるので見直しておいてくださいー。

2022-06-20 07:52 UTC, taguchi commented on index.html
> +            <i class="bi bi-gear-fill"></i>
設定という感じではないので、`<i class="bi bi-apple"></i>`がいいかも。

2022-06-20 07:52 UTC, taguchi commented on mac.js
> +  const arrPC = {
変数名つけるのが面倒なので、

```
const items = [
  {
    "title": "PC操作の基本用語",
    "items": [ .... ],
  }, {
    "title": "Macの画面",
...
```

として一つの大きな配列のなかにオブジェクトを複数いれるといいかも？

2022-06-20 07:52 UTC, taguchi commented on mac.js
> +      a.setAttribute('target', '_blank');
お・・・`setAttribute()`はどちらかというと非推奨かな。

普通に

```
a.target = "_blank";
a.href = "";
```

がよいです。

2022-06-20 07:52 UTC, taguchi commented on mac.js
> +  renderCheckList(arrPC);
ここらへんは大きな配列を`forEach()`で回せばうまくいきそうです。

2022-06-21 02:58 UTC, hxtksg commented on index.html
> +            <i class="bi bi-gear-fill"></i>
しまった、ギアアイコンのままでしたね...
Apple アイコンと Windows アイコンを使うようにいたします！

2022-06-21 07:18 UTC, hxtksg commented on mac.js
> +  const arrPC = {
1つのオブジェクトにまとめるほうが断然楽ですね！そのようにいたしますー

2022-06-21 07:18 UTC, hxtksg commented on mac.js
> +  const p = document.querySelector('p');
こちら、構造を少し変えました！

2022-06-21 07:25 UTC, hxtksg commented
リファクタリング完了しました！ ご確認よろしくお願いいたします。 @taguchi

2022-06-21 07:31 UTC, taguchi requested changes
細かいですが、`a`タグ不要かな、と思いますー

2022-06-21 07:31 UTC, taguchi commented on beginner_pc_mac_v4.html
> +    <div id="target"></div>
良いと思います！

2022-06-21 07:31 UTC, taguchi commented on mac.js
> +  const checkLists = [
ばっちりですね！

2022-06-21 07:31 UTC, taguchi commented on mac.js
> +      a.href = '';
このあたり、すべてコメント化してもいいかも？

2022-06-21 07:31 UTC, taguchi commented on mac.js
> +      a.href = '';
`a`タグ不要なので。

2022-06-21 07:45 UTC, hxtksg commented
確かに `a` タグいりませんでしたね！コメントアウトして push しましたー。 @taguchi

2022-06-21 10:09 UTC, hxtksg commented
チェックリストを修正して push しました！ @taguchi 

`checklist.md` ファイルに過去のチェックリストを保存してあります。

2022-06-22 02:59 UTC, merged