Add windows ver
dotinstall/setup pull request #4
Opened 2022-06-29 05:27 UTC by rigoooon

2022-06-29 05:59 UTC, taguchi requested changes
Reviewしたので修正してみましょう。

2022-06-29 05:59 UTC, taguchi commented on checklist_win.html
> +    <title>PCの基礎知識チェックリスト macOS編</title>
Windows編、にしましょう。

2022-06-29 05:59 UTC, taguchi commented on checklist_win.html
> +        PCの基礎知識チェックリスト macOS編
これもWindows編、で。

2022-06-29 05:59 UTC, taguchi commented on checklist_win.html
> +        <a href=""><i class="bi bi-windows"></i></a>
こちらからはリンクとる。

2022-06-29 05:59 UTC, taguchi commented on checklist_win.html
> +        <i class="bi bi-apple"></i>
ここにはリンクはりましょう。

2022-06-29 05:59 UTC, taguchi commented on checklist_win.html
> +            '自分のPCに搭載されているCPU（プロセッサ）がIntel、M1、M2のどれか答えることができる',
これは削除していいかも。

2022-06-29 05:59 UTC, taguchi commented on checklist_win.html
> +            'Finderでファイルの拡張子を表示させることができる',
Finderじゃないかな。

2022-06-29 05:59 UTC, taguchi commented on checklist_win.html
> +            '起動したいアプリケーションをSpotlightから検索することができる',
Spotlightでもないかな。

2022-06-29 05:59 UTC, taguchi commented on checklist_win.html
> +            'Finderを使って「デスクトップ」にあるファイルやフォルダを表示することができる',
このあたりもWindowsにあわせましょう。

2022-06-29 05:59 UTC, taguchi commented on checklist_win.html
> +            'プレビューアプリを使ってファイルの中身を確認することができる',
これもWindowsに適したものに。

2022-06-29 05:59 UTC, taguchi commented on checklist_win.html
> +            'macOSの機能を使って、任意の範囲のスクリーンショットを撮ることができる',
ここもWindowsに合わせる。

2022-06-29 05:59 UTC, taguchi commented on checklist_win.html
> +          '「/」「\\」の名前をそれぞれ言うことができて、キーボードで入力することができる',
BackslashはWindowsで打てるかな...？

2022-06-29 06:02 UTC, rigoooon commented
@taguchi 
あ、すみません！
とりあえずファイルを作っただけで、コードの編集はなに１つしていませんでした。
これから取り掛かります！

2022-06-29 06:05 UTC, taguchi commented
> @taguchi
> あ、すみません！
> とりあえずファイルを作ってpull req の練習をしただけで、コードの編集はなに１つしていません。
> 今コードを編集しているところです。

OK！

2022-06-30 03:58 UTC, taguchi requested changes
2点ほど。よろしく！

2022-06-30 03:58 UTC, taguchi commented on checklist_win.html
> +    <title>PCの基礎知識チェックリスト macOS編</title>
ここも変更する必要あり。

2022-06-30 03:58 UTC, taguchi commented on checklist_win.html
> +            '自分のPCに搭載されているCPU（プロセッサ）がIntel、M1、M2のどれか答えることができる',
WindowsにM1, M2はないかも？削除してもいいような気がする。

2022-06-30 14:36 UTC, merged